### PR TITLE
pushing intensity.py and associated test

### PR DESCRIPTION
**Pull request by dennisbrookner**
I think this should do it, but let me know if there are any functionality and/or style things I'm missing.

### CODE REVIEW

**Comment by dennisbrookner** [comment]
Sorry for making a huge mess of this! I'll fix it tomorrow

**Comment by JBGreisman** [comment]
sounds good -- ping me when you're to have this looked at

**Comment by dennisbrookner** [comment]
This is now functional! @JBGreisman let me know if I'm handling input types correctly; it seemed consistent with other similar functions to accept lists, `numpy` arrays, and `rs.DataSeries`.

**Review by JBGreisman — CHANGES_REQUESTED** [review]
I think the API for this should match the other functions in `rs.algorithms` (see `merge()` or `scale_merged_intensities()`):

`compute_intensity_from_structurefactor(dataset, f_key="F", sigf_key="SigF")`

I think this will have the advantage of streamlining your error handling -- you just need to confirm that the selected columns have the correct MTZDtype. You can implement the function as it is, and return a new `DataSet` with desired columns. All this has the advantage that in the future we can implement this to be "smarter" about the distributions if we want --  that may require multiplicities, spacegroups, etc. 

I think this should return a DataSet because otherwise you lose information about the Miller indices, spacegroup, cell, etc. Please let me know if you agree/disagree.

**Comment by dennisbrookner** [comment]
I am going to make the changes above, and push them to a new branch `intensities-clean`. This is hopefully the easier path than trying to untangle the above PR.

**Comment by dennisbrookner** [comment]
See #156

**Comment by JBGreisman** [comment]
@dennisbrookner Can this be closed now that a new PR has been started?

**Comment by dennisbrookner** [comment]
Yes, closing this

**Pull request closed without merging**
